import type { Bill, Debt, IncomeSource, AssistanceProgram, Reminder, NoireInventoryItem, NoireLead, HomeIssue, CashUpdate } from '@/types/database'

export const DEMO_USER_ID = 'demo-user-00000000-0000-0000-0000-000000000000'

export const DEMO_DATA = {
  cashOnHand: 234,

  cashUpdates: [
    {
      id: 'cash-1',
      user_id: DEMO_USER_ID,
      amount: 234,
      note: 'Current cash on hand',
      source: 'manual',
      created_at: new Date().toISOString(),
    },
  ] as CashUpdate[],

  bills: [
    {
      id: 'bill-1',
      user_id: DEMO_USER_ID,
      name: 'Rent',
      amount: 1100,
      due_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      category: 'rent',
      status: 'overdue',
      priority: 1,
      note: 'Past due — contact landlord immediately',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'bill-2',
      user_id: DEMO_USER_ID,
      name: 'Light Bill (PPL/PECO)',
      amount: 180,
      due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      category: 'utilities',
      status: 'pending',
      priority: 2,
      note: 'LIHEAP assistance may cover this',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'bill-3',
      user_id: DEMO_USER_ID,
      name: 'Phone (owed to Mary)',
      amount: 60,
      due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      category: 'phone',
      status: 'pending',
      priority: 3,
      note: 'Mary covered the phone bill — need to repay',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Bill[],

  debts: [
    {
      id: 'debt-1',
      user_id: DEMO_USER_ID,
      creditor_name: 'Dana',
      amount: 100,
      amount_remaining: 100,
      debt_type: 'personal',
      status: 'active',
      note: 'Personal loan',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'debt-2',
      user_id: DEMO_USER_ID,
      creditor_name: 'Reggie',
      amount: 100,
      amount_remaining: 100,
      debt_type: 'personal',
      status: 'active',
      note: 'Personal loan',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'debt-3',
      user_id: DEMO_USER_ID,
      creditor_name: 'Mary (phone bill)',
      amount: 60,
      amount_remaining: 60,
      debt_type: 'personal',
      status: 'active',
      note: 'Mary covered phone bill',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Debt[],

  incomeSources: [
    {
      id: 'income-1',
      user_id: DEMO_USER_ID,
      name: 'Unemployment Benefits (PA UC)',
      type: 'unemployment',
      amount: 450,
      frequency: 'biweekly',
      status: 'active',
      expected_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      note: 'Certify Tuesday — deposit expected Thursday',
      created_at: new Date().toISOString(),
    },
    {
      id: 'income-2',
      user_id: DEMO_USER_ID,
      name: 'Noire Brand Revenue',
      type: 'noire',
      amount: null,
      frequency: 'irregular',
      status: 'active',
      expected_date: null,
      note: 'Active leads in pipeline — 2 hot prospects',
      created_at: new Date().toISOString(),
    },
  ] as IncomeSource[],

  assistancePrograms: [
    {
      id: 'assist-1',
      user_id: DEMO_USER_ID,
      program_name: 'LIHEAP Energy Assistance',
      type: 'utilities',
      status: 'applied',
      amount: 180,
      appointment_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      contact_name: null,
      contact_phone: null,
      note: 'Appointment scheduled — bring utility bills, ID, proof of income, lease',
      created_at: new Date().toISOString(),
    },
    {
      id: 'assist-2',
      user_id: DEMO_USER_ID,
      program_name: 'Township Emergency Assistance',
      type: 'housing',
      status: 'applied',
      amount: null,
      appointment_date: null,
      contact_name: null,
      contact_phone: null,
      note: 'Application submitted — pending landlord section completion',
      created_at: new Date().toISOString(),
    },
  ] as AssistanceProgram[],

  reminders: [
    {
      id: 'rem-1',
      user_id: DEMO_USER_ID,
      title: 'Certify Unemployment',
      body: 'Log in to PA UC portal and certify for the week',
      due_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'critical',
      category: 'income',
      completed: false,
      completed_at: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'rem-2',
      user_id: DEMO_USER_ID,
      title: 'LIHEAP Appointment',
      body: 'Bring: utility bills, ID, proof of income, lease',
      due_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'high',
      category: 'assistance',
      completed: false,
      completed_at: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'rem-3',
      user_id: DEMO_USER_ID,
      title: 'Contact Landlord — Rent',
      body: 'Discuss payment plan or timeline for overdue rent',
      due_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'critical',
      category: 'housing',
      completed: false,
      completed_at: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'rem-4',
      user_id: DEMO_USER_ID,
      title: 'Follow up — Marcus T. (Noire)',
      body: 'Send tee + cap bundle pricing. He seemed ready.',
      due_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'medium',
      category: 'noire',
      completed: false,
      completed_at: null,
      created_at: new Date().toISOString(),
    },
  ] as Reminder[],

  noireInventory: [
    {
      id: 'inv-1',
      user_id: DEMO_USER_ID,
      name: 'Noire Classic Tee — Black L',
      sku: 'NR-TEE-BLK-L',
      category: 'apparel',
      quantity: 3,
      cost_per_unit: 12,
      price: 45,
      status: 'active',
      note: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'inv-2',
      user_id: DEMO_USER_ID,
      name: 'Noire Fitted Cap — Black',
      sku: 'NR-CAP-BLK',
      category: 'accessories',
      quantity: 2,
      cost_per_unit: 8,
      price: 35,
      status: 'active',
      note: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'inv-3',
      user_id: DEMO_USER_ID,
      name: 'Noire Identity Hoodie — XL',
      sku: 'NR-HOOD-XL',
      category: 'apparel',
      quantity: 1,
      cost_per_unit: 25,
      price: 85,
      status: 'active',
      note: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'inv-4',
      user_id: DEMO_USER_ID,
      name: 'Noire Sticker Pack',
      sku: 'NR-STICK-01',
      category: 'print',
      quantity: 15,
      cost_per_unit: 1,
      price: 8,
      status: 'active',
      note: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as NoireInventoryItem[],

  noireLeads: [
    {
      id: 'lead-1',
      user_id: DEMO_USER_ID,
      name: 'Marcus T.',
      contact: '@marcust_ig',
      platform: 'Instagram',
      interest: 'Custom tee + cap bundle',
      status: 'warm',
      estimated_value: 80,
      note: 'DM convo going — follow up Friday with pricing',
      created_at: new Date().toISOString(),
    },
    {
      id: 'lead-2',
      user_id: DEMO_USER_ID,
      name: 'Keisha Events Co.',
      contact: 'keisha@events.co',
      platform: 'Email',
      interest: 'Bulk event merch order (10+ units)',
      status: 'hot',
      estimated_value: 450,
      note: 'Wants quote for 10 units — this could be major',
      created_at: new Date().toISOString(),
    },
  ] as NoireLead[],

  homeIssues: [
    {
      id: 'issue-1',
      user_id: DEMO_USER_ID,
      title: 'Car — Fuel Pump Replacement (Meineke)',
      description: 'Meineke quoted $980 for fuel pump replacement. Car is not running. Need transport or financing.',
      category: 'appliance',
      priority: 'high',
      status: 'open',
      reported_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      resolved_date: null,
      note: 'Quote from Meineke: $980 parts + labor',
      created_at: new Date().toISOString(),
    },
  ] as HomeIssue[],

  threats: [
    { id: 't1', title: 'Rent Overdue', description: '$1,100 rent past due', amount: 1100, priority: 'critical' as const, type: 'bill' as const },
    { id: 't2', title: 'Car Down', description: 'Fuel pump out — Meineke quote $980', amount: 980, priority: 'high' as const, type: 'car' as const },
    { id: 't3', title: 'Light Bill Due', description: '$180 due in 3 days', amount: 180, priority: 'high' as const, type: 'bill' as const },
  ],

  opportunities: [
    { id: 'o1', title: 'Unemployment Deposit', description: 'Certify Tuesday, deposit Thursday', amount: 450, expectedDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), type: 'income' as const },
    { id: 'o2', title: 'LIHEAP Assistance', description: 'Appointment in 2 days — may cover light bill', amount: 180, type: 'assistance' as const },
    { id: 'o3', title: 'Keisha Events Lead', description: 'Hot Noire lead — $450 potential', amount: 450, type: 'noire' as const },
  ],

  nextMoves: [
    { order: 1, title: 'Contact Landlord', description: 'Discuss rent payment plan for overdue $1,100', category: 'housing', priority: 'critical' as const },
    { order: 2, title: 'Certify Unemployment Tuesday', description: 'Log into PA UC portal — $450 deposit expected Thursday', category: 'income', priority: 'critical' as const },
    { order: 3, title: 'Attend LIHEAP Appointment', description: 'Bring ID, bills, lease — may eliminate $180 utility bill', category: 'assistance', priority: 'high' as const },
  ],
}
